[project]
name = "learning-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Elbazoune", email = "bazounef@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
]

[project.scripts]
learning-langgraph = "learning_langgraph:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
